#!/bin/sh
# whileread_file
# initialise variables
SAVEDIFS=$IFS
IFS=:
HOLD_FILE=hold_file
HOLD_MATCH="James lenod"
INPUT_FILE=names.txt

# create a new HOLD_FILE each time, in case script is continuously run
>$HOLD_FILE

while read NAME DEPT ID
do
  # echo all information into holdfile with redirection
  echo $NAME $DEPT $ID >>$HOLD_FILE
  # is it a match ???
  if [ "$NAME" = "NAME_MATCH" ];then
    # yes then nice exit
    echo "all entries up to and including $NAME_MATCH are in %HOLD_FILE"
    exit 0
  fi
done < $INPUT_FILE
#restore IFS
IFS=$SAVEDIFS
