#!/bin/sh
# password
# show use of the restoring stty environment
SAVEDSTTY=`stty -g`
stty -echo
echo -e "\nGive me that password :\c"
read PASSWD
echo -e "\nyour password is $PASSWD"
stty $SAVEDSTTY
